import type { NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import NoSSR from "react-no-ssr";

const Home: NextPage = () => {
  const [stage, setStage] = useState(0);
  const [mood, setMood] = useState(0);
  const [speed, setSpeed] = useState(0);
  const [emotion, setEmotion] = useState(0);

  const onMood1 = () => {
    setMood(mood + 1);
    setStage(stage + 1);
  };
  const onMood2 = () => {
    setMood(mood + 2);
    setStage(stage + 1);
  };

  const onSpeed1 = () => {
    setSpeed(speed + 1);
    setStage(stage + 1);
  };
  const onSpeed2 = () => {
    setSpeed(speed + 2);
    setStage(stage + 1);
  };

  const onEmotion1 = () => {
    setEmotion(emotion + 1);
    setStage(stage + 1);
  };
  const onEmotion2 = () => {
    setEmotion(emotion + 2);
    setStage(stage + 1);
  };
  const onEmotion3 = () => {
    setEmotion(emotion + 3);
    setStage(stage + 1);
  };

  const bodys = {
    marginTop: "0%",
    marginLeft: "0%",
    marginRight: "0%",
    marginBottom: "0%",
    background: "#EFF2F8 0% 0% no-repeat padding-box",
    opacity: "1",
  };

  const text1 = {
    marginTop: "8%",
    marginLeft: "20%",
    width: "60%",
    height: "21%",

    textAlign: "center",
    font: "normal normal bold 200%/150% Helvetica Neue",
    letterSpacing: "0%",
    color: "#121212",
    opacity: "1",
  };
  const moodBox = {
    width: "97%",
    height: "20%",
    display: "flex",
    justifyContent: "center",
    marginLeft: "2%",
  };
  const mood1 = {
    width: "44%",
    height: "100%",
    opacity: "1",
    margin: "3%",
  };
  const mood2 = {
    width: "44%",
    height: "100%",
    opacity: "1",
    margin: "3%",
  };
  const emotion1 = {
    width: "100%",
    height: "100%",
    opacity: "1",
    margin: "3%",
  };
  const emotionText = {
    width: "100%",
    height: "100%",
  };
  const container = {
    width: "100%",
    height: "100%",
    margin: "3%",
    display: "flex",
    flexDirection: "column",
  };
  const mood_common = {
    width: "100%",
    height: "100%",
  };
  const text2 = {
    marginTop: "8%",
    marginLeft: "0%",
    width: "100%",
    height: "21%",

    textAlign: "center",
    font: "normal normal bold 200%/150% Helvetica Neue",
    letterSpacing: "0%",
    color: "#121212",
    opacity: "1",
  };
  const text3 = {
    marginTop: "8%",
    marginLeft: "0%",
    width: "100%",
    height: "21%",

    textAlign: "center",
    font: "normal normal bold 200%/150% Helvetica Neue",
    letterSpacing: "0%",
    color: "#121212",
    opacity: "1",
  };
  if (stage == 0) {
    return (
      <div>
        <Head>
          <title>Spotify Music Recommendation</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NoSSR>
          <body style={bodys}>
            <p style={text1}>What kind of mood do you like?</p>
            <div style={moodBox}>
              <div style={mood1}>
                <img
                  onClick={onMood1}
                  style={mood_common}
                  src="/mood1.png"
                ></img>
              </div>
              <div style={mood2}>
                <img
                  onClick={onMood2}
                  style={mood_common}
                  src="/mood2.png"
                ></img>
              </div>
            </div>
          </body>
        </NoSSR>

        <footer></footer>
      </div>
    );
  } else if (stage == 1) {
    return (
      <div>
        <Head>
          <title>Spotify Music Recommendation</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NoSSR>
          <body style={bodys}>
            <p style={text2}>How fast do you want your music to be?</p>
            <div style={moodBox}>
              <div style={mood1}>
                <img
                  onClick={onSpeed1}
                  style={mood_common}
                  src="/slow.png"
                ></img>
              </div>
              <div style={mood2}>
                <img
                  onClick={onSpeed2}
                  style={mood_common}
                  src="/fast.png"
                ></img>
              </div>
            </div>
          </body>
        </NoSSR>

        <footer></footer>
      </div>
    );
  } else if (stage == 2) {
    return (
      <div>
        <Head>
          <title>Spotify Music Recommendation</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NoSSR>
          <body style={bodys}>
            <p style={text3}>What is your current emotional state?</p>
            <div style={moodBox}>
              <div style={container}>
                <div style={emotion1}>
                  <img
                    onClick={onEmotion1}
                    style={mood_common}
                    src="/depressed.png"
                  ></img>
                </div>
                <p style={text3}>I`m depressed</p>
              </div>
              <div style={container}>
                <div style={emotion1}>
                  <img
                    onClick={onEmotion2}
                    style={mood_common}
                    src="/normal.png"
                  ></img>
                </div>
              </div>
              <div style={container}>
                <div style={emotion1}>
                  <img
                    onClick={onEmotion3}
                    style={mood_common}
                    src="/excited.png"
                  ></img>
                </div>
              </div>
            </div>
          </body>
        </NoSSR>

        <footer></footer>
      </div>
    );
  }
};

export default Home;
