import type { NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import NoSSR from "react-no-ssr";
import { css } from "@emotion/react";
import TrackSelect from "../components/filter/TrackSelect";
import ImageSelect from "../components/filter/MoodSelect";
import EmotionSelect from "../components/filter/EmotionSelect";

const Tracks = [
  {
    track_name: "DNA",
    artist_name: "방탄소년단",
    album_image: "/a1.jfif",
  },
  {
    track_name: "Shape of You",
    artist_name: "Ed Sheeran",
    album_image: "/a2.jfif",
  },
  {
    track_name: "TOMBOY",
    artist_name: "(여자) 아이들",
    album_image: "/a3.jfif",
  },
  {
    track_name: "Okay Dokey",
    artist_name: "MINO, 지코",
    album_image: "/a4.jfif",
  },
  {
    track_name: "선물",
    artist_name: "멜로망스",
    album_image: "/a5.jfif",
  },
];

const Emotions = [
  {
    description: "I'm depressed",
    image_url: "/depressed.png",
    emotion_number: 1,
  },
  {
    description: "I'm feeling normal",
    image_url: "/normal.png",
    emotion_number: 2,
  },
  {
    description: "I'm excited!",
    image_url: "/excited.png",
    emotion_number: 3,
  },
];

const Home: NextPage = () => {
  const [stage, setStage] = useState(-1);
  const [mood, setMood] = useState(0);
  const [speed, setSpeed] = useState(0);
  const [emotion, setEmotion] = useState(0);
  const [music, setMusic] = useState("");

  const onBack = () => {
    setStage((prev) => {
      if (prev === -1) return prev;
      return prev - 1;
    });
  };

  return (
    <div style={bodyss}>
      <Head>
        <title>Spotify Music Recommendation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NoSSR>
        <body>
          <main
            css={css`
              display: flex;
              width: 100vw;
              height: 100vh;
              position: relative;
              flex-direction: column;
            `}
          >
            <img
              onClick={onBack}
              css={css`
                width: 48px;
                height: 48px;
                left: 48px;
                top: 48px;
                position: absolute;
              `}
              src="/back.png"
            />
            <button
              css={css`
                width: 60px;
                height: 48px;
                color: #3751ff;
                font-size: 22px;
                margin: 0 auto;
                margin-top: 24px;
                cursor: pointer;
                position: absolute;
                right: 48px;
                top: 36px;
              `}
            >
              Reset
            </button>
            {stage === -1 && (
              <>
                <p style={text1}>Which song do you like the most?</p>
                <div
                  css={css`
                    display: flex;
                    width: 100%;
                    justify-content: center;
                    gap: 24px;
                  `}
                >
                  {Tracks.map((track) => (
                    <TrackSelect
                      key={track.track_name}
                      track_name={track.track_name}
                      artist_name={track.artist_name}
                      selected={music === track.track_name}
                      album_image={track.album_image}
                      onClick={() => {
                        setMusic(track.track_name);
                        setTimeout(() => {
                          setStage((prev) => prev + 1);
                        }, 500);
                      }}
                    />
                  ))}
                </div>
              </>
            )}
            {stage === 0 && (
              <>
                <p style={text1}>What kind of mood do you like?</p>
                <div
                  css={css`
                    display: flex;
                    gap: 58px;
                    justify-content: center;
                  `}
                >
                  <ImageSelect
                    image_url="/mood1.png"
                    selected={mood === 1}
                    onClick={() => {
                      setMood(1);
                      setTimeout(() => {
                        setStage(stage + 1);
                      }, 500);
                    }}
                  />
                  <ImageSelect
                    image_url="/mood2.png"
                    selected={mood === 2}
                    onClick={() => {
                      setMood(2);
                      setTimeout(() => {
                        setStage(stage + 1);
                      }, 500);
                    }}
                  />
                </div>
              </>
            )}
            {stage === 1 && (
              <>
                <p style={text2}>How fast do you want your music to be?</p>
                <div
                  css={css`
                    display: flex;
                    gap: 58px;
                    justify-content: center;
                  `}
                >
                  <ImageSelect
                    selected={speed === 1}
                    onClick={() => {
                      setSpeed(1);
                      setTimeout(() => {
                        setStage(stage + 1);
                      }, 500);
                    }}
                    image_url="/slow.png"
                  />
                  <ImageSelect
                    selected={speed === 2}
                    onClick={() => {
                      setSpeed(2);
                      setTimeout(() => {
                        setStage(stage + 1);
                      }, 500);
                    }}
                    image_url="/fast.png"
                  />
                </div>
              </>
            )}
            {stage === 2 && (
              <>
                <p style={text3}>What is your current emotional state?</p>
                <div
                  css={css`
                    display: flex;
                    gap: 32px;
                    justify-content: center;
                  `}
                >
                  {Emotions.map((item) => (
                    <EmotionSelect
                      key={item.emotion_number}
                      selected={emotion === item.emotion_number}
                      onClick={() => {
                        setEmotion(item.emotion_number);
                      }}
                      description={item.description}
                      image_url={item.image_url}
                    />
                  ))}
                </div>
              </>
            )}
          </main>
        </body>
      </NoSSR>
    </div>
  );
};

export default Home;

const text1 = {
  marginTop: "5%",
  marginLeft: "20%",
  width: "60%",
  height: "21%",

  textAlign: "center",
  font: "normal normal bold 200%/150% Helvetica Neue",
  letterSpacing: "0%",
  color: "#121212",
  opacity: "1",
};
const text2 = {
  marginTop: "5%",
  marginLeft: "0%",
  width: "100%",
  height: "21%",

  textAlign: "center",
  font: "normal normal bold 200%/150% Helvetica Neue",
  letterSpacing: "0%",
  color: "#121212",
  opacity: "1",
};

const text3 = {
  marginTop: "5%",
  marginLeft: "2%",
  width: "100%",
  height: "21%",

  textAlign: "center",
  font: "normal normal bold 200%/150% Helvetica Neue",
  letterSpacing: "0%",
  color: "#121212",
  opacity: "1",
};
const bodyss = {
  height: "100vh",
  marginTop: "0%",
  marginLeft: "0%",
  marginRight: "0%",
  marginBottom: "0%",
  background: "#EFF2F8 0% 0% no-repeat padding-box",
  opacity: "1",
};
