spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music-recmnd
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

logging.level:
  org.hibernate.SQL: debug
